name = "form-pdf-app"
main = "worker/index.js"
compatibility_date = "2024-09-23"

# Cloudflare Pages / Workers static assets configuration
[assets]
directory = "./dist"
binding = "ASSETS"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "form_db"
database_id = "02357075-e5e8-4e30-8c5f-aec1ded0153f"

# Environment variables
[vars]
ENVIRONMENT = "production"
